/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TyGiaNgoaiTeRouteImport } from './routes/ty-gia-ngoai-te'
import { Route as TyGiaNganHangRouteImport } from './routes/ty-gia-ngan-hang'
import { Route as TienDienTuRouteImport } from './routes/tien-dien-tu'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StocksRouteImport } from './routes/stocks'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QuyDoiTienTeRouteImport } from './routes/quy-doi-tien-te'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MienTruTrachNhiemRouteImport } from './routes/mien-tru-trach-nhiem'
import { Route as LienHeRouteImport } from './routes/lien-he'
import { Route as GoldRouteImport } from './routes/gold'
import { Route as GiaVangRouteImport } from './routes/gia-vang'
import { Route as ForexRouteImport } from './routes/forex'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DieuKhoanSuDungRouteImport } from './routes/dieu-khoan-su-dung'
import { Route as CryptoRouteImport } from './routes/crypto'
import { Route as ConverterRouteImport } from './routes/converter'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChungKhoanRouteImport } from './routes/chung-khoan'
import { Route as ChinhSachBaoMatRouteImport } from './routes/chinh-sach-bao-mat'
import { Route as BankRatesRouteImport } from './routes/bank-rates'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaiSanSymbolRouteImport } from './routes/tai-san.$symbol'
import { Route as AssetSymbolRouteImport } from './routes/asset.$symbol'
import { Route as ApiPublicXauRouteImport } from './routes/api/public/xau'
import { Route as ApiPublicStocksRouteImport } from './routes/api/public/stocks'
import { Route as ApiPublicPairHistoryRouteImport } from './routes/api/public/pair-history'
import { Route as ApiPublicGoldRouteImport } from './routes/api/public/gold'
import { Route as ApiPublicForexRouteImport } from './routes/api/public/forex'
import { Route as ApiPublicCryptoChartRouteImport } from './routes/api/public/crypto-chart'
import { Route as ApiPublicCryptoRouteImport } from './routes/api/public/crypto'
import { Route as ApiPublicBankRatesRouteImport } from './routes/api/public/bank-rates'

const TyGiaNgoaiTeRoute = TyGiaNgoaiTeRouteImport.update({
  id: '/ty-gia-ngoai-te',
  path: '/ty-gia-ngoai-te',
  getParentRoute: () => rootRouteImport,
} as any)
const TyGiaNganHangRoute = TyGiaNganHangRouteImport.update({
  id: '/ty-gia-ngan-hang',
  path: '/ty-gia-ngan-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const TienDienTuRoute = TienDienTuRouteImport.update({
  id: '/tien-dien-tu',
  path: '/tien-dien-tu',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksRoute = StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QuyDoiTienTeRoute = QuyDoiTienTeRouteImport.update({
  id: '/quy-doi-tien-te',
  path: '/quy-doi-tien-te',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MienTruTrachNhiemRoute = MienTruTrachNhiemRouteImport.update({
  id: '/mien-tru-trach-nhiem',
  path: '/mien-tru-trach-nhiem',
  getParentRoute: () => rootRouteImport,
} as any)
const LienHeRoute = LienHeRouteImport.update({
  id: '/lien-he',
  path: '/lien-he',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldRoute = GoldRouteImport.update({
  id: '/gold',
  path: '/gold',
  getParentRoute: () => rootRouteImport,
} as any)
const GiaVangRoute = GiaVangRouteImport.update({
  id: '/gia-vang',
  path: '/gia-vang',
  getParentRoute: () => rootRouteImport,
} as any)
const ForexRoute = ForexRouteImport.update({
  id: '/forex',
  path: '/forex',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DieuKhoanSuDungRoute = DieuKhoanSuDungRouteImport.update({
  id: '/dieu-khoan-su-dung',
  path: '/dieu-khoan-su-dung',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoRoute = CryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const ConverterRoute = ConverterRouteImport.update({
  id: '/converter',
  path: '/converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChungKhoanRoute = ChungKhoanRouteImport.update({
  id: '/chung-khoan',
  path: '/chung-khoan',
  getParentRoute: () => rootRouteImport,
} as any)
const ChinhSachBaoMatRoute = ChinhSachBaoMatRouteImport.update({
  id: '/chinh-sach-bao-mat',
  path: '/chinh-sach-bao-mat',
  getParentRoute: () => rootRouteImport,
} as any)
const BankRatesRoute = BankRatesRouteImport.update({
  id: '/bank-rates',
  path: '/bank-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiSanSymbolRoute = TaiSanSymbolRouteImport.update({
  id: '/tai-san/$symbol',
  path: '/tai-san/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetSymbolRoute = AssetSymbolRouteImport.update({
  id: '/asset/$symbol',
  path: '/asset/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicXauRoute = ApiPublicXauRouteImport.update({
  id: '/api/public/xau',
  path: '/api/public/xau',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStocksRoute = ApiPublicStocksRouteImport.update({
  id: '/api/public/stocks',
  path: '/api/public/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPairHistoryRoute = ApiPublicPairHistoryRouteImport.update({
  id: '/api/public/pair-history',
  path: '/api/public/pair-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoldRoute = ApiPublicGoldRouteImport.update({
  id: '/api/public/gold',
  path: '/api/public/gold',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicForexRoute = ApiPublicForexRouteImport.update({
  id: '/api/public/forex',
  path: '/api/public/forex',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCryptoChartRoute = ApiPublicCryptoChartRouteImport.update({
  id: '/api/public/crypto-chart',
  path: '/api/public/crypto-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCryptoRoute = ApiPublicCryptoRouteImport.update({
  id: '/api/public/crypto',
  path: '/api/public/crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBankRatesRoute = ApiPublicBankRatesRouteImport.update({
  id: '/api/public/bank-rates',
  path: '/api/public/bank-rates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bank-rates': typeof BankRatesRoute
  '/chinh-sach-bao-mat': typeof ChinhSachBaoMatRoute
  '/chung-khoan': typeof ChungKhoanRoute
  '/contact': typeof ContactRoute
  '/converter': typeof ConverterRoute
  '/crypto': typeof CryptoRoute
  '/dieu-khoan-su-dung': typeof DieuKhoanSuDungRoute
  '/disclaimer': typeof DisclaimerRoute
  '/forex': typeof ForexRoute
  '/gia-vang': typeof GiaVangRoute
  '/gold': typeof GoldRoute
  '/lien-he': typeof LienHeRoute
  '/mien-tru-trach-nhiem': typeof MienTruTrachNhiemRoute
  '/privacy': typeof PrivacyRoute
  '/quy-doi-tien-te': typeof QuyDoiTienTeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stocks': typeof StocksRoute
  '/terms': typeof TermsRoute
  '/tien-dien-tu': typeof TienDienTuRoute
  '/ty-gia-ngan-hang': typeof TyGiaNganHangRoute
  '/ty-gia-ngoai-te': typeof TyGiaNgoaiTeRoute
  '/asset/$symbol': typeof AssetSymbolRoute
  '/tai-san/$symbol': typeof TaiSanSymbolRoute
  '/api/public/bank-rates': typeof ApiPublicBankRatesRoute
  '/api/public/crypto': typeof ApiPublicCryptoRoute
  '/api/public/crypto-chart': typeof ApiPublicCryptoChartRoute
  '/api/public/forex': typeof ApiPublicForexRoute
  '/api/public/gold': typeof ApiPublicGoldRoute
  '/api/public/pair-history': typeof ApiPublicPairHistoryRoute
  '/api/public/stocks': typeof ApiPublicStocksRoute
  '/api/public/xau': typeof ApiPublicXauRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bank-rates': typeof BankRatesRoute
  '/chinh-sach-bao-mat': typeof ChinhSachBaoMatRoute
  '/chung-khoan': typeof ChungKhoanRoute
  '/contact': typeof ContactRoute
  '/converter': typeof ConverterRoute
  '/crypto': typeof CryptoRoute
  '/dieu-khoan-su-dung': typeof DieuKhoanSuDungRoute
  '/disclaimer': typeof DisclaimerRoute
  '/forex': typeof ForexRoute
  '/gia-vang': typeof GiaVangRoute
  '/gold': typeof GoldRoute
  '/lien-he': typeof LienHeRoute
  '/mien-tru-trach-nhiem': typeof MienTruTrachNhiemRoute
  '/privacy': typeof PrivacyRoute
  '/quy-doi-tien-te': typeof QuyDoiTienTeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stocks': typeof StocksRoute
  '/terms': typeof TermsRoute
  '/tien-dien-tu': typeof TienDienTuRoute
  '/ty-gia-ngan-hang': typeof TyGiaNganHangRoute
  '/ty-gia-ngoai-te': typeof TyGiaNgoaiTeRoute
  '/asset/$symbol': typeof AssetSymbolRoute
  '/tai-san/$symbol': typeof TaiSanSymbolRoute
  '/api/public/bank-rates': typeof ApiPublicBankRatesRoute
  '/api/public/crypto': typeof ApiPublicCryptoRoute
  '/api/public/crypto-chart': typeof ApiPublicCryptoChartRoute
  '/api/public/forex': typeof ApiPublicForexRoute
  '/api/public/gold': typeof ApiPublicGoldRoute
  '/api/public/pair-history': typeof ApiPublicPairHistoryRoute
  '/api/public/stocks': typeof ApiPublicStocksRoute
  '/api/public/xau': typeof ApiPublicXauRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bank-rates': typeof BankRatesRoute
  '/chinh-sach-bao-mat': typeof ChinhSachBaoMatRoute
  '/chung-khoan': typeof ChungKhoanRoute
  '/contact': typeof ContactRoute
  '/converter': typeof ConverterRoute
  '/crypto': typeof CryptoRoute
  '/dieu-khoan-su-dung': typeof DieuKhoanSuDungRoute
  '/disclaimer': typeof DisclaimerRoute
  '/forex': typeof ForexRoute
  '/gia-vang': typeof GiaVangRoute
  '/gold': typeof GoldRoute
  '/lien-he': typeof LienHeRoute
  '/mien-tru-trach-nhiem': typeof MienTruTrachNhiemRoute
  '/privacy': typeof PrivacyRoute
  '/quy-doi-tien-te': typeof QuyDoiTienTeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stocks': typeof StocksRoute
  '/terms': typeof TermsRoute
  '/tien-dien-tu': typeof TienDienTuRoute
  '/ty-gia-ngan-hang': typeof TyGiaNganHangRoute
  '/ty-gia-ngoai-te': typeof TyGiaNgoaiTeRoute
  '/asset/$symbol': typeof AssetSymbolRoute
  '/tai-san/$symbol': typeof TaiSanSymbolRoute
  '/api/public/bank-rates': typeof ApiPublicBankRatesRoute
  '/api/public/crypto': typeof ApiPublicCryptoRoute
  '/api/public/crypto-chart': typeof ApiPublicCryptoChartRoute
  '/api/public/forex': typeof ApiPublicForexRoute
  '/api/public/gold': typeof ApiPublicGoldRoute
  '/api/public/pair-history': typeof ApiPublicPairHistoryRoute
  '/api/public/stocks': typeof ApiPublicStocksRoute
  '/api/public/xau': typeof ApiPublicXauRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bank-rates'
    | '/chinh-sach-bao-mat'
    | '/chung-khoan'
    | '/contact'
    | '/converter'
    | '/crypto'
    | '/dieu-khoan-su-dung'
    | '/disclaimer'
    | '/forex'
    | '/gia-vang'
    | '/gold'
    | '/lien-he'
    | '/mien-tru-trach-nhiem'
    | '/privacy'
    | '/quy-doi-tien-te'
    | '/sitemap.xml'
    | '/stocks'
    | '/terms'
    | '/tien-dien-tu'
    | '/ty-gia-ngan-hang'
    | '/ty-gia-ngoai-te'
    | '/asset/$symbol'
    | '/tai-san/$symbol'
    | '/api/public/bank-rates'
    | '/api/public/crypto'
    | '/api/public/crypto-chart'
    | '/api/public/forex'
    | '/api/public/gold'
    | '/api/public/pair-history'
    | '/api/public/stocks'
    | '/api/public/xau'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bank-rates'
    | '/chinh-sach-bao-mat'
    | '/chung-khoan'
    | '/contact'
    | '/converter'
    | '/crypto'
    | '/dieu-khoan-su-dung'
    | '/disclaimer'
    | '/forex'
    | '/gia-vang'
    | '/gold'
    | '/lien-he'
    | '/mien-tru-trach-nhiem'
    | '/privacy'
    | '/quy-doi-tien-te'
    | '/sitemap.xml'
    | '/stocks'
    | '/terms'
    | '/tien-dien-tu'
    | '/ty-gia-ngan-hang'
    | '/ty-gia-ngoai-te'
    | '/asset/$symbol'
    | '/tai-san/$symbol'
    | '/api/public/bank-rates'
    | '/api/public/crypto'
    | '/api/public/crypto-chart'
    | '/api/public/forex'
    | '/api/public/gold'
    | '/api/public/pair-history'
    | '/api/public/stocks'
    | '/api/public/xau'
  id:
    | '__root__'
    | '/'
    | '/bank-rates'
    | '/chinh-sach-bao-mat'
    | '/chung-khoan'
    | '/contact'
    | '/converter'
    | '/crypto'
    | '/dieu-khoan-su-dung'
    | '/disclaimer'
    | '/forex'
    | '/gia-vang'
    | '/gold'
    | '/lien-he'
    | '/mien-tru-trach-nhiem'
    | '/privacy'
    | '/quy-doi-tien-te'
    | '/sitemap.xml'
    | '/stocks'
    | '/terms'
    | '/tien-dien-tu'
    | '/ty-gia-ngan-hang'
    | '/ty-gia-ngoai-te'
    | '/asset/$symbol'
    | '/tai-san/$symbol'
    | '/api/public/bank-rates'
    | '/api/public/crypto'
    | '/api/public/crypto-chart'
    | '/api/public/forex'
    | '/api/public/gold'
    | '/api/public/pair-history'
    | '/api/public/stocks'
    | '/api/public/xau'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BankRatesRoute: typeof BankRatesRoute
  ChinhSachBaoMatRoute: typeof ChinhSachBaoMatRoute
  ChungKhoanRoute: typeof ChungKhoanRoute
  ContactRoute: typeof ContactRoute
  ConverterRoute: typeof ConverterRoute
  CryptoRoute: typeof CryptoRoute
  DieuKhoanSuDungRoute: typeof DieuKhoanSuDungRoute
  DisclaimerRoute: typeof DisclaimerRoute
  ForexRoute: typeof ForexRoute
  GiaVangRoute: typeof GiaVangRoute
  GoldRoute: typeof GoldRoute
  LienHeRoute: typeof LienHeRoute
  MienTruTrachNhiemRoute: typeof MienTruTrachNhiemRoute
  PrivacyRoute: typeof PrivacyRoute
  QuyDoiTienTeRoute: typeof QuyDoiTienTeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StocksRoute: typeof StocksRoute
  TermsRoute: typeof TermsRoute
  TienDienTuRoute: typeof TienDienTuRoute
  TyGiaNganHangRoute: typeof TyGiaNganHangRoute
  TyGiaNgoaiTeRoute: typeof TyGiaNgoaiTeRoute
  AssetSymbolRoute: typeof AssetSymbolRoute
  TaiSanSymbolRoute: typeof TaiSanSymbolRoute
  ApiPublicBankRatesRoute: typeof ApiPublicBankRatesRoute
  ApiPublicCryptoRoute: typeof ApiPublicCryptoRoute
  ApiPublicCryptoChartRoute: typeof ApiPublicCryptoChartRoute
  ApiPublicForexRoute: typeof ApiPublicForexRoute
  ApiPublicGoldRoute: typeof ApiPublicGoldRoute
  ApiPublicPairHistoryRoute: typeof ApiPublicPairHistoryRoute
  ApiPublicStocksRoute: typeof ApiPublicStocksRoute
  ApiPublicXauRoute: typeof ApiPublicXauRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ty-gia-ngoai-te': {
      id: '/ty-gia-ngoai-te'
      path: '/ty-gia-ngoai-te'
      fullPath: '/ty-gia-ngoai-te'
      preLoaderRoute: typeof TyGiaNgoaiTeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ty-gia-ngan-hang': {
      id: '/ty-gia-ngan-hang'
      path: '/ty-gia-ngan-hang'
      fullPath: '/ty-gia-ngan-hang'
      preLoaderRoute: typeof TyGiaNganHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tien-dien-tu': {
      id: '/tien-dien-tu'
      path: '/tien-dien-tu'
      fullPath: '/tien-dien-tu'
      preLoaderRoute: typeof TienDienTuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks': {
      id: '/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quy-doi-tien-te': {
      id: '/quy-doi-tien-te'
      path: '/quy-doi-tien-te'
      fullPath: '/quy-doi-tien-te'
      preLoaderRoute: typeof QuyDoiTienTeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mien-tru-trach-nhiem': {
      id: '/mien-tru-trach-nhiem'
      path: '/mien-tru-trach-nhiem'
      fullPath: '/mien-tru-trach-nhiem'
      preLoaderRoute: typeof MienTruTrachNhiemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lien-he': {
      id: '/lien-he'
      path: '/lien-he'
      fullPath: '/lien-he'
      preLoaderRoute: typeof LienHeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold': {
      id: '/gold'
      path: '/gold'
      fullPath: '/gold'
      preLoaderRoute: typeof GoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gia-vang': {
      id: '/gia-vang'
      path: '/gia-vang'
      fullPath: '/gia-vang'
      preLoaderRoute: typeof GiaVangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forex': {
      id: '/forex'
      path: '/forex'
      fullPath: '/forex'
      preLoaderRoute: typeof ForexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dieu-khoan-su-dung': {
      id: '/dieu-khoan-su-dung'
      path: '/dieu-khoan-su-dung'
      fullPath: '/dieu-khoan-su-dung'
      preLoaderRoute: typeof DieuKhoanSuDungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto': {
      id: '/crypto'
      path: '/crypto'
      fullPath: '/crypto'
      preLoaderRoute: typeof CryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/converter': {
      id: '/converter'
      path: '/converter'
      fullPath: '/converter'
      preLoaderRoute: typeof ConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chung-khoan': {
      id: '/chung-khoan'
      path: '/chung-khoan'
      fullPath: '/chung-khoan'
      preLoaderRoute: typeof ChungKhoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chinh-sach-bao-mat': {
      id: '/chinh-sach-bao-mat'
      path: '/chinh-sach-bao-mat'
      fullPath: '/chinh-sach-bao-mat'
      preLoaderRoute: typeof ChinhSachBaoMatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-rates': {
      id: '/bank-rates'
      path: '/bank-rates'
      fullPath: '/bank-rates'
      preLoaderRoute: typeof BankRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tai-san/$symbol': {
      id: '/tai-san/$symbol'
      path: '/tai-san/$symbol'
      fullPath: '/tai-san/$symbol'
      preLoaderRoute: typeof TaiSanSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset/$symbol': {
      id: '/asset/$symbol'
      path: '/asset/$symbol'
      fullPath: '/asset/$symbol'
      preLoaderRoute: typeof AssetSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/xau': {
      id: '/api/public/xau'
      path: '/api/public/xau'
      fullPath: '/api/public/xau'
      preLoaderRoute: typeof ApiPublicXauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stocks': {
      id: '/api/public/stocks'
      path: '/api/public/stocks'
      fullPath: '/api/public/stocks'
      preLoaderRoute: typeof ApiPublicStocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pair-history': {
      id: '/api/public/pair-history'
      path: '/api/public/pair-history'
      fullPath: '/api/public/pair-history'
      preLoaderRoute: typeof ApiPublicPairHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gold': {
      id: '/api/public/gold'
      path: '/api/public/gold'
      fullPath: '/api/public/gold'
      preLoaderRoute: typeof ApiPublicGoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/forex': {
      id: '/api/public/forex'
      path: '/api/public/forex'
      fullPath: '/api/public/forex'
      preLoaderRoute: typeof ApiPublicForexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crypto-chart': {
      id: '/api/public/crypto-chart'
      path: '/api/public/crypto-chart'
      fullPath: '/api/public/crypto-chart'
      preLoaderRoute: typeof ApiPublicCryptoChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crypto': {
      id: '/api/public/crypto'
      path: '/api/public/crypto'
      fullPath: '/api/public/crypto'
      preLoaderRoute: typeof ApiPublicCryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bank-rates': {
      id: '/api/public/bank-rates'
      path: '/api/public/bank-rates'
      fullPath: '/api/public/bank-rates'
      preLoaderRoute: typeof ApiPublicBankRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BankRatesRoute: BankRatesRoute,
  ChinhSachBaoMatRoute: ChinhSachBaoMatRoute,
  ChungKhoanRoute: ChungKhoanRoute,
  ContactRoute: ContactRoute,
  ConverterRoute: ConverterRoute,
  CryptoRoute: CryptoRoute,
  DieuKhoanSuDungRoute: DieuKhoanSuDungRoute,
  DisclaimerRoute: DisclaimerRoute,
  ForexRoute: ForexRoute,
  GiaVangRoute: GiaVangRoute,
  GoldRoute: GoldRoute,
  LienHeRoute: LienHeRoute,
  MienTruTrachNhiemRoute: MienTruTrachNhiemRoute,
  PrivacyRoute: PrivacyRoute,
  QuyDoiTienTeRoute: QuyDoiTienTeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StocksRoute: StocksRoute,
  TermsRoute: TermsRoute,
  TienDienTuRoute: TienDienTuRoute,
  TyGiaNganHangRoute: TyGiaNganHangRoute,
  TyGiaNgoaiTeRoute: TyGiaNgoaiTeRoute,
  AssetSymbolRoute: AssetSymbolRoute,
  TaiSanSymbolRoute: TaiSanSymbolRoute,
  ApiPublicBankRatesRoute: ApiPublicBankRatesRoute,
  ApiPublicCryptoRoute: ApiPublicCryptoRoute,
  ApiPublicCryptoChartRoute: ApiPublicCryptoChartRoute,
  ApiPublicForexRoute: ApiPublicForexRoute,
  ApiPublicGoldRoute: ApiPublicGoldRoute,
  ApiPublicPairHistoryRoute: ApiPublicPairHistoryRoute,
  ApiPublicStocksRoute: ApiPublicStocksRoute,
  ApiPublicXauRoute: ApiPublicXauRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
