/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetSymbolRouteImport } from './routes/asset.$symbol'
import { Route as ApiPublicGoldRouteImport } from './routes/api/public/gold'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetSymbolRoute = AssetSymbolRouteImport.update({
  id: '/asset/$symbol',
  path: '/asset/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoldRoute = ApiPublicGoldRouteImport.update({
  id: '/api/public/gold',
  path: '/api/public/gold',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asset/$symbol': typeof AssetSymbolRoute
  '/api/public/gold': typeof ApiPublicGoldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asset/$symbol': typeof AssetSymbolRoute
  '/api/public/gold': typeof ApiPublicGoldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asset/$symbol': typeof AssetSymbolRoute
  '/api/public/gold': typeof ApiPublicGoldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/asset/$symbol' | '/api/public/gold'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/asset/$symbol' | '/api/public/gold'
  id: '__root__' | '/' | '/asset/$symbol' | '/api/public/gold'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetSymbolRoute: typeof AssetSymbolRoute
  ApiPublicGoldRoute: typeof ApiPublicGoldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset/$symbol': {
      id: '/asset/$symbol'
      path: '/asset/$symbol'
      fullPath: '/asset/$symbol'
      preLoaderRoute: typeof AssetSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gold': {
      id: '/api/public/gold'
      path: '/api/public/gold'
      fullPath: '/api/public/gold'
      preLoaderRoute: typeof ApiPublicGoldRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetSymbolRoute: AssetSymbolRoute,
  ApiPublicGoldRoute: ApiPublicGoldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
